# Generated by Django 4.2.2 on 2023-06-20 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manuf_model', models.CharField(max_length=128)),
                ('location_desc', models.CharField(max_length=128)),
                ('location_geo_lat', models.FloatField()),
                ('location_geo_lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('timestamp', models.DateTimeField(verbose_name='Date/time observed')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temperature.temperaturesensor')),
            ],
        ),
    ]
